# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Value.create([
  {name: 'computer', model: 'model 1',    option: '',    usp: '1', cost: 2,   ton: 1,  tl:  5, ep: 0},
  {name: 'computer', model: 'model 1fib', option: 'fib', usp: '1', cost: 3,   ton: 2,  tl:  5, ep: 0},
  {name: 'computer', model: 'model 1bis', option: 'bis', usp: '1', cost: 4,   ton: 1,  tl:  6, ep: 0},
  {name: 'computer', model: 'model 2',    option: '',    usp: '2', cost: 9,   ton: 2,  tl:  7, ep: 0},
  {name: 'computer', model: 'model 2fib', option: 'fib', usp: '2', cost: 14,  ton: 4,  tl:  7, ep: 0},
  {name: 'computer', model: 'model 2bis', option: 'bis', usp: '2', cost: 18,  ton: 2,  tl:  8, ep: 0},
  {name: 'computer', model: 'model 3',    option: '',    usp: '3', cost: 18,  ton: 3,  tl:  9, ep: 1},
  {name: 'computer', model: 'model 3fib', option: 'fib', usp: '3', cost: 27,  ton: 6,  tl:  9, ep: 1},
  {name: 'computer', model: 'model 4',    option: '',    usp: '4', cost: 30,  ton: 4,  tl: 10, ep: 2},
  {name: 'computer', model: 'model 4fib', option: 'fib', usp: '4', cost: 45,  ton: 8,  tl: 10, ep: 2},
  {name: 'computer', model: 'model 5',    option: '',    usp: '5', cost: 45,  ton: 5,  tl: 11, ep: 3},
  {name: 'computer', model: 'model 5fib', option: 'fib', usp: '5', cost: 68,  ton: 10, tl: 11, ep: 3},
  {name: 'computer', model: 'model 6',    option: '',    usp: '6', cost: 55,  ton: 7,  tl: 12, ep: 5},
  {name: 'computer', model: 'model 6fib', option: 'fib', usp: '6', cost: 83,  ton: 14, tl: 12, ep: 5},
  {name: 'computer', model: 'model 7',    option: '',    usp: '7', cost: 80,  ton: 9,  tl: 13, ep: 7},
  {name: 'computer', model: 'model 7fib', option: 'fib', usp: '7', cost: 100, ton: 18, tl: 13, ep: 7},
  {name: 'computer', model: 'model 8',    option: '',    usp: '8', cost: 110, ton: 11, tl: 14, ep: 9},
  {name: 'computer', model: 'model 8fib', option: 'fib', usp: '8', cost: 140, ton: 22, tl: 14, ep: 9},
  {name: 'computer', model: 'model 9',    option: '',    usp: '9', cost: 140, ton: 13, tl: 15, ep: 12},
  {name: 'computer', model: 'model 9fib', option: 'fib', usp: '9', cost: 200, ton: 26, tl: 15, ep: 12},
  
  {name: 'particle accelerator', model:  'barbette', usp: '1', cost:  4, ton:  5, tl: 14, ep:  5, crew: 1},
  {name: 'particle accelerator', model:  'barbette', usp: '2', cost:  8, ton: 10, tl: 14, ep: 10, crew: 1},
  {name: 'particle accelerator', model:  'barbette', usp: '3', cost: 16, ton: 20, tl: 14, ep: 20, crew: 1},
  {name: 'particle accelerator', model:  'barbette', usp: '4', cost: 24, ton: 30, tl: 14, ep: 30, crew: 1},
  {name: 'particle accelerator', model:  'barbette', usp: '5', cost: 32, ton: 40, tl: 14, ep: 40, crew: 1},
  {name: 'particle accelerator', model:  'barbette', usp: '6', cost: 40, ton: 50, tl: 14, ep: 50, crew: 1},
  {name: 'particle accelerator', model:  'turret', usp: '2', cost:  3, ton:  3, tl: 15, ep:  5, crew: 1},
  {name: 'particle accelerator', model:  'turret', usp: '3', cost:  6, ton:  6, tl: 15, ep: 10, crew: 1},
  {name: 'particle accelerator', model:  'turret', usp: '4', cost:  8, ton: 12, tl: 15, ep: 20, crew: 1},
  {name: 'particle accelerator', model:  'turret', usp: '5', cost: 12, ton: 18, tl: 15, ep: 30, crew: 1},
  {name: 'particle accelerator', model:  'turret', usp: '6', cost: 16, ton: 24, tl: 15, ep: 40, crew: 1},
  {name: 'particle accelerator', model:  'turret', usp: '7', cost: 20, ton: 30, tl: 15, ep: 50, crew: 1},
  {name: 'particle accelerator', model:  '50-ton bay', usp: '3', cost: 20, ton:  50, tl: 10, ep:  30, crew: 2},
  {name: 'particle accelerator', model:  '50-ton bay', usp: '4', cost: 20, ton:  50, tl: 12, ep:  30, crew: 2},
  {name: 'particle accelerator', model:  '50-ton bay', usp: '5', cost: 20, ton:  50, tl: 14, ep:  30, crew: 2},
  {name: 'particle accelerator', model: '100-ton bay', usp: '6', cost: 35, ton: 100, tl:  8, ep:  60, crew: 2},
  {name: 'particle accelerator', model: '100-ton bay', usp: '7', cost: 35, ton: 100, tl: 10, ep:  60, crew: 2},
  {name: 'particle accelerator', model: '100-ton bay', usp: '8', cost: 35, ton: 100, tl: 12, ep:  60, crew: 2},
  {name: 'particle accelerator', model: '100-ton bay', usp: '9', cost: 35, ton: 100, tl: 14, ep:  60, crew: 2},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'A', cost: 3500, ton: 5500, tl:  8, ep:  500, crew: 55},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'B', cost: 3000, ton: 5000, tl:  9, ep:  500, crew: 50},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'C', cost: 2400, ton: 4500, tl: 10, ep:  500, crew: 45},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'D', cost: 1500, ton: 4000, tl: 11, ep:  600, crew: 40},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'E', cost: 1200, ton: 3500, tl: 12, ep:  600, crew: 35},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'F', cost: 1200, ton: 3000, tl: 13, ep:  600, crew: 30},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'G', cost:  800, ton: 2500, tl: 14, ep:  700, crew: 25},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'H', cost:  500, ton: 2500, tl: 15, ep:  700, crew: 25},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'J', cost: 3000, ton: 5000, tl: 10, ep:  800, crew: 50},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'K', cost: 2000, ton: 4500, tl: 11, ep:  800, crew: 45},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'L', cost: 1600, ton: 4000, tl: 12, ep:  800, crew: 40},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'M', cost: 1200, ton: 3500, tl: 13, ep:  900, crew: 35},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'N', cost: 1000, ton: 3000, tl: 14, ep:  900, crew: 30},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'P', cost:  800, ton: 2500, tl: 15, ep:  900, crew: 25},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'Q', cost: 2000, ton: 4500, tl: 12, ep: 1000, crew: 45},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'R', cost: 1500, ton: 4000, tl: 13, ep: 1000, crew: 40},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'S', cost: 1200, ton: 3500, tl: 14, ep: 1000, crew: 35},
  {name: 'particle accelerator', model: 'spinal mount', usp: 'T', cost: 1000, ton: 3000, tl: 15, ep: 1000, crew: 30},

  {name: 'meson gun', model:  '50-ton bay', usp: '4', cost: 50, ton:  50, tl: 15, ep:  100, crew: 2},
  {name: 'meson gun', model: '100-ton bay', usp: '3', cost: 70, ton: 100, tl: 13, ep:  200, crew: 2},
  {name: 'meson gun', model: '100-ton bay', usp: '5', cost: 70, ton: 100, tl: 14, ep:  200, crew: 2},
  {name: 'meson gun', model: '100-ton bay', usp: '9', cost: 70, ton: 100, tl: 15, ep:  200, crew: 2},
  {name: 'meson gun', model: 'spinal mount', usp: 'A', cost: 10000, ton: 5000, tl: 11, ep:  500, crew: 50},
  {name: 'meson gun', model: 'spinal mount', usp: 'B', cost: 12000, ton: 8000, tl: 11, ep:  600, crew: 80},
  {name: 'meson gun', model: 'spinal mount', usp: 'C', cost:  3000, ton: 2000, tl: 12, ep:  600, crew: 20},
  {name: 'meson gun', model: 'spinal mount', usp: 'D', cost:  5000, ton: 5000, tl: 12, ep:  700, crew: 50},
  {name: 'meson gun', model: 'spinal mount', usp: 'E', cost:   800, ton: 1000, tl: 13, ep:  700, crew: 10},
  {name: 'meson gun', model: 'spinal mount', usp: 'F', cost:  1000, ton: 2000, tl: 13, ep:  800, crew: 20},
  {name: 'meson gun', model: 'spinal mount', usp: 'G', cost:   400, ton: 1000, tl: 14, ep:  800, crew: 10},
  {name: 'meson gun', model: 'spinal mount', usp: 'H', cost:   600, ton: 2000, tl: 14, ep:  900, crew: 20},
  {name: 'meson gun', model: 'spinal mount', usp: 'J', cost:   400, ton: 1000, tl: 15, ep:  900, crew: 10},
  {name: 'meson gun', model: 'spinal mount', usp: 'K', cost: 10000, ton: 8000, tl: 12, ep: 1000, crew: 80},
  {name: 'meson gun', model: 'spinal mount', usp: 'L', cost:  3000, ton: 5000, tl: 13, ep: 1000, crew: 50},
  {name: 'meson gun', model: 'spinal mount', usp: 'M', cost:   800, ton: 4000, tl: 14, ep: 1000, crew: 40},
  {name: 'meson gun', model: 'spinal mount', usp: 'N', cost:   600, ton: 2000, tl: 15, ep: 1000, crew: 20},
  {name: 'meson gun', model: 'spinal mount', usp: 'P', cost:  5000, ton: 8000, tl: 13, ep: 1100, crew: 80},
  {name: 'meson gun', model: 'spinal mount', usp: 'Q', cost:  1000, ton: 7000, tl: 14, ep: 1100, crew: 70},
  {name: 'meson gun', model: 'spinal mount', usp: 'R', cost:   800, ton: 5000, tl: 15, ep: 1100, crew: 50},
  {name: 'meson gun', model: 'spinal mount', usp: 'S', cost:  2000, ton: 8000, tl: 14, ep: 1200, crew: 80},
  {name: 'meson gun', model: 'spinal mount', usp: 'T', cost:  1000, ton: 7000, tl: 15, ep: 1200, crew: 70},
  
  {name: 'repulsor', model: '100-ton bay', usp: '2', cost: 10, ton: 100, tl: 10, ep: 10, crew: 2},
  {name: 'repulsor', model: '100-ton bay', usp: '4', cost: 10, ton: 100, tl: 11, ep: 10, crew: 2},
  {name: 'repulsor', model: '100-ton bay', usp: '6', cost: 10, ton: 100, tl: 12, ep: 10, crew: 2},
  {name: 'repulsor', model: '100-ton bay', usp: '7', cost: 10, ton: 100, tl: 13, ep: 10, crew: 2},
  {name: 'repulsor', model: '100-ton bay', usp: '8', cost: 10, ton: 100, tl: 14, ep: 10, crew: 2},
  {name: 'repulsor', model: '100-ton bay', usp: '9', cost: 10, ton: 100, tl: 15, ep: 10, crew: 2},
  {name: 'repulsor', model:  '50-ton bay', usp: '3', cost:  6, ton:  50, tl: 14, ep:  5, crew: 2},
  {name: 'repulsor', model:  '50-ton bay', usp: '5', cost:  6, ton:  50, tl: 15, ep:  5, crew: 2},
  
  {name: 'missile', model: 'turret', usp: '1', cost:  0.75, ton:  1, tl: 7, crew: 1},
  {name: 'missile', model: 'turret', usp: '2', cost:  2.25, ton:  1, tl: 7, crew: 1},
  {name: 'missile', model: 'turret', usp: '3', cost:  4.50, ton:  1, tl: 7, crew: 1},
  {name: 'missile', model: 'turret', usp: '4', cost:  9.00, ton:  1, tl: 7, crew: 1},
  {name: 'missile', model: 'turret', usp: '5', cost: 13.50, ton:  1, tl: 7, crew: 1},
  {name: 'missile', model: 'turret', usp: '6', cost: 22.50, ton:  1, tl: 7, crew: 1},
  {name: 'missile', model: '100-ton bay', usp: '7', cost: 20, ton: 100, tl:  7, crew: 2},
  {name: 'missile', model: '100-ton bay', usp: '8', cost: 20, ton: 100, tl: 10, crew: 2},
  {name: 'missile', model: '100-ton bay', usp: '9', cost: 20, ton: 100, tl: 12, crew: 2},
  {name: 'missile', model:  '50-ton bay', usp: '7', cost: 12, ton:  50, tl: 10, crew: 2},
  {name: 'missile', model:  '50-ton bay', usp: '8', cost: 12, ton:  50, tl: 12, crew: 2},
  {name: 'missile', model:  '50-ton bay', usp: '9', cost: 12, ton:  50, tl: 14, crew: 2},
  
  {name: 'plasma gun', model: 'turret', usp: '1', cost:  1.5, ton:  2, tl: 10, crew: 1},
  {name: 'plasma gun', model: 'turret', usp: '2', cost:  6.0, ton:  4, tl: 10, crew: 1},
  {name: 'plasma gun', model: 'turret', usp: '3', cost: 15.0, ton: 10, tl: 10, crew: 1},
  {name: 'plasma gun', model: 'turret', usp: '4', cost: 24.0, ton: 16, tl: 10, crew: 1},
  {name: 'plasma gun', model: 'turret', usp: '5', cost: 35.0, ton: 20, tl: 10, crew: 1},
  {name: 'plasma gun', model: '50-ton bay', usp: '4', cost: 5, ton: 50, tl: 10, ep: 10, crew: 2},
  {name: 'plasma gun', model: '50-ton bay', usp: '5', cost: 5, ton: 50, tl: 11, ep: 10, crew: 2},
  {name: 'plasma gun', model: '50-ton bay', usp: '6', cost: 5, ton: 50, tl: 12, ep: 10, crew: 2},
  
  {name: 'fusion gun', model: 'turret', usp: '4', cost:  2, ton:  2, tl: 12, crew: 1},
  {name: 'fusion gun', model: 'turret', usp: '5', cost:  8, ton:  4, tl: 12, crew: 1},
  {name: 'fusion gun', model: 'turret', usp: '6', cost: 20, ton: 10, tl: 12, crew: 1},
  {name: 'fusion gun', model: 'turret', usp: '7', cost: 32, ton: 16, tl: 12, crew: 1},
  {name: 'fusion gun', model: 'turret', usp: '8', cost: 40, ton: 20, tl: 12, crew: 1},
  {name: 'fusion gun', model: '50-ton bay', usp: '7', cost: 8, ton: 50, tl: 12, ep: 20, crew: 2},
  {name: 'fusion gun', model: '50-ton bay', usp: '8', cost: 8, ton: 50, tl: 13, ep: 20, crew: 2},
  {name: 'fusion gun', model: '50-ton bay', usp: '9', cost: 8, ton: 50, tl: 14, ep: 20, crew: 2},
  
  {name: 'beam laser', model: 'turret', usp: '1', cost:  1, ton:  1, tl: 7, ep:  1, crew: 1},
  {name: 'beam laser', model: 'turret', usp: '2', cost:  2, ton:  1, tl: 7, ep:  2, crew: 1},
  {name: 'beam laser', model: 'turret', usp: '3', cost:  3, ton:  1, tl: 7, ep:  3, crew: 1},
  {name: 'beam laser', model: 'turret', usp: '4', cost:  6, ton:  2, tl: 7, ep:  6, crew: 1},
  {name: 'beam laser', model: 'turret', usp: '5', cost: 10, ton:  4, tl: 7, ep: 10, crew: 1},
  {name: 'beam laser', model: 'turret', usp: '6', cost: 15, ton:  5, tl: 7, ep: 15, crew: 1},
  {name: 'beam laser', model: 'turret', usp: '7', cost: 21, ton:  7, tl: 7, ep: 21, crew: 1},
  {name: 'beam laser', model: 'turret', usp: '8', cost: 30, ton: 10, tl: 7, ep: 30, crew: 1},
  
  {name: 'pulse laser', model: 'turret', usp: '1', cost:  0.5, ton:  1, tl: 7, ep:  1, crew: 1},
  {name: 'pulse laser', model: 'turret', usp: '2', cost:  1.5, ton:  1, tl: 7, ep:  3, crew: 1},
  {name: 'pulse laser', model: 'turret', usp: '3', cost:  3.0, ton:  2, tl: 7, ep:  6, crew: 1},
  {name: 'pulse laser', model: 'turret', usp: '4', cost:  5.0, ton:  4, tl: 7, ep: 10, crew: 1},
  {name: 'pulse laser', model: 'turret', usp: '5', cost: 10.5, ton:  7, tl: 7, ep: 21, crew: 1},
  {name: 'pulse laser', model: 'turret', usp: '6', cost: 15.0, ton: 10, tl: 7, ep: 30, crew: 1},
  
  {name: 'sandcaster', model: 'turret', usp: '1', cost:  0.25, ton:  1, tl: 7, crew: 1},
  {name: 'sandcaster', model: 'turret', usp: '2', cost:  0.75, ton:  1, tl: 7, crew: 1},
  {name: 'sandcaster', model: 'turret', usp: '3', cost:  1.50, ton:  2, tl: 7, crew: 1},
  {name: 'sandcaster', model: 'turret', usp: '4', cost:  2.00, ton:  3, tl: 7, crew: 1},
  {name: 'sandcaster', model: 'turret', usp: '5', cost:  2.50, ton:  4, tl: 7, crew: 1},
  {name: 'sandcaster', model: 'turret', usp: '6', cost:  5.00, ton:  7, tl: 7, crew: 1},
  {name: 'sandcaster', model: 'turret', usp: '7', cost:  7.50, ton: 10, tl: 7, crew: 1},
  
  {name: 'nuclear dampers', usp: '1', cost: 50, ton: 50, tl: 12, ep: 10, crew: 4},
  {name: 'nuclear dampers', usp: '2', cost: 40, ton: 15, tl: 13, ep: 20, crew: 4},
  {name: 'nuclear dampers', usp: '3', cost: 45, ton: 20, tl: 13, ep: 30, crew: 4},
  {name: 'nuclear dampers', usp: '4', cost: 30, ton:  8, tl: 14, ep: 40, crew: 4},
  {name: 'nuclear dampers', usp: '5', cost: 35, ton: 10, tl: 14, ep: 50, crew: 4},
  {name: 'nuclear dampers', usp: '6', cost: 38, ton: 12, tl: 14, ep: 60, crew: 4},
  {name: 'nuclear dampers', usp: '7', cost: 30, ton: 10, tl: 15, ep: 70, crew: 4},
  {name: 'nuclear dampers', usp: '8', cost: 40, ton: 15, tl: 15, ep: 80, crew: 4},
  {name: 'nuclear dampers', usp: '9', cost: 50, ton: 20, tl: 15, ep: 90, crew: 4},
  
  {name: 'meson screens', usp: '1', cost: 80, ton: 90, tl: 12, crew: 4},
  {name: 'meson screens', usp: '2', cost: 50, ton: 30, tl: 13, crew: 4},
  {name: 'meson screens', usp: '3', cost: 55, ton: 45, tl: 13, crew: 4},
  {name: 'meson screens', usp: '4', cost: 40, ton: 16, tl: 14, crew: 4},
  {name: 'meson screens', usp: '5', cost: 45, ton: 20, tl: 14, crew: 4},
  {name: 'meson screens', usp: '6', cost: 50, ton: 24, tl: 14, crew: 4},
  {name: 'meson screens', usp: '7', cost: 40, ton: 20, tl: 15, crew: 4},
  {name: 'meson screens', usp: '8', cost: 50, ton: 30, tl: 15, crew: 4},
  {name: 'meson screens', usp: '9', cost: 60, ton: 40, tl: 15, crew: 4},
  
  {name: 'force field', usp: '1', cost:  400, ton: 10, tl: 15, crew: 4},
  {name: 'force field', usp: '2', cost:  600, ton: 15, tl: 15, crew: 4},
  {name: 'force field', usp: '3', cost:  800, ton: 20, tl: 15, crew: 4},
  {name: 'force field', usp: '4', cost: 1000, ton: 25, tl: 15, crew: 4},
  {name: 'force field', usp: '5', cost: 1000000, ton: 20, tl: 16, crew: 4},
  {name: 'force field', usp: '6', cost: 1000000, ton: 30, tl: 16, crew: 4},
  {name: 'force field', usp: '7', cost: 1000000, ton: 35, tl: 16, crew: 4},
])

Empire.create([
  {name: 'Imperium'}
])

Techlevel.create([
  {tl: '0'},{tl: '1'},{tl: '2'},{tl: '3'},{tl: '4'},{tl: '5'},
  {tl: '6'},{tl: '7'},{tl: '8'},{tl: '9'},{tl: 'A'},{tl: 'B'},
  {tl: 'C'},{tl: 'D'},{tl: 'E'},{tl: 'F'},{tl: 'G'}])
	
Uspcode.create([
  {usp: '0'}, {usp: '1'}, {usp: '2'}, {usp: '3'}, {usp: '4'}, {usp: '5'},
  {usp: '6'}, {usp: '7'}, {usp: '8'}, {usp: '9'}, {usp: 'A'}, {usp: 'B'},
  {usp: 'C'}, {usp: 'D'}, {usp: 'E'}, {usp: 'F'}, {usp: 'G'}, {usp: 'H'},
  {usp: 'J'}, {usp: 'K'}, {usp: 'L'}, {usp: 'M'}, {usp: 'N'}, {usp: 'P'},
  {usp: 'Q'}, {usp: 'R'}, {usp: 'S'}, {usp: 'T'}, {usp: 'U'}, {usp: 'V'},
  {usp: 'W'}, {usp: 'X'}, {usp: 'Y'}, {usp: 'Z'}])

Componentname.create([
  {name: 'bridge'},
  {name: 'computer'},
  {name: 'drivejump'},
  {name: 'drivemaneouver'},
  {name: 'powerplant'},
  {name: 'nucleardamper'},
  {name: 'mesonscreen'},
  {name: 'blackglobe'},
  {name: 'laser'},
  {name: 'missile'},
  {name: 'energy'},
  {name: 'pa'},
  {name: 'meson'},
  {name: 'repulsor'},
  {name: 'fuelscoops'},
  {name: 'configuration'},
  {name: 'hullarmour'},
  {name: 'controlcouches'},
  {name: 'purificationplant'},
  {name: 'fueljump'},
  {name: 'fuelpower'},
  {name: 'fuelcargo'},
  {name: 'cargo'},
  {name: 'crew'},
  {name: 'passengers'},
  {name: 'hanger'},
  {name: 'craft'}
])

Primaryor.create([
  {rank: 'primary'}, 
  {rank: 'secondary'}, 
  {rank: 'tertiary'}])

Primarytype.create([
	{usp: 'A', name: 'Merchant'},
	{usp: 'B', name: 'Battle'},
	{usp: 'C', name: 'Cruiser'},
	{usp: 'C', name: 'Carrier'},
	{usp: 'D', name: 'Destroyer'},
	{usp: 'E', name: 'Escort'},
	{usp: 'F', name: 'Frigate'},
	{usp: 'F', name: 'Fighter'},
	{usp: 'G', name: 'Gig'},
	{usp: 'G', name: 'Refinery'},
	{usp: 'I', name: 'Intruder'},
	{usp: 'J', name: 'Intruder'},
	{usp: 'K', name: 'Pinnace'},
	{usp: 'L', name: 'Corvette'},
	{usp: 'L', name: 'Lab'},
	{usp: 'M', name: 'Merchant'},
	{usp: 'P', name: 'Planetoid'},
	{usp: 'Q', name: 'Auxiliary'},
	{usp: 'R', name: 'Liner'},
	{usp: 'S', name: 'Scout'},
	{usp: 'S', name: 'Station'},
	{usp: 'T', name: 'Tanker'},
	{usp: 'T', name: 'Tender'},
	{usp: 'W', name: 'Barge'},
	{usp: 'X', name: 'Express'},
	{usp: 'Y', name: 'Yacht'}
])

Secondarytype.create([
	{usp: 'A', name: 'Armored'},
	{usp: 'B', name: 'Battle'},
	{usp: 'B', name: 'Boat'},
	{usp: 'C', name: 'Cruiser'},
	{usp: 'C', name: 'Close'},
	{usp: 'D', name: 'Destroyer'},
	{usp: 'E', name: 'Escort'},
	{usp: 'F', name: 'Fast'},
	{usp: 'F', name: 'Fleet'},
	{usp: 'G', name: 'Gunned'},
	{usp: 'H', name: 'Heavy'},
	{usp: 'L', name: 'Leader'},
	{usp: 'L', name: 'Light'},
	{usp: 'M', name: 'Missile'},
	{usp: 'N', name: 'Non-standard'},
	{usp: 'P', name: 'Provincial'},
	{usp: 'Q', name: 'Decoy'},
	{usp: 'R', name: 'Raider'},
	{usp: 'S', name: 'Strike'},
	{usp: 'T', name: 'Troop'},
	{usp: 'T', name: 'Transport'},
	{usp: 'U', name: 'Unpowered'},
	{usp: 'V', name: 'Vehicle'},
	{usp: 'Y', name: 'Shuttle'},
	{usp: 'Y', name: 'Cutter'},
	{usp: 'Z', name: 'Experimental'}])